mod helpers;
pub mod manual_err;
pub mod manual_expect;
pub mod manual_expect_err;
pub mod manual_is_err;
pub mod manual_is_none;
pub mod manual_is_ok;
pub mod manual_is_some;
pub mod manual_ok;
pub mod manual_ok_or;
pub mod manual_unwrap_or_default;
