name: Nightly

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-with-nightly-cairo:
    name: Test nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Upgrade Cairo to latest main commit
        run: cargo xtask upgrade cairo --rev $(git ls-remote --refs "https://github.com/starkware-libs/cairo" main | awk '{print $1}')
      - name: Get corelib
        run: git clone https://github.com/starkware-libs/cairo
      - name: Run cargo test
        run: CORELIB_PATH="$(pwd)/cairo/corelib/src" cargo test

  notify_failed:
    runs-on: ubuntu-latest
    if: always() && needs.test-with-nightly-cairo.result == 'failure'
    needs: test-with-nightly-cairo
    steps:
      - name: Notify the team about workflow failure
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_SCARB_NIGHTLY_CHECK_FAILURE_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
