name: Website Deploy

on:
  workflow_call:
    inputs:
      target_branch:
        description: "Git branch to deploy from"
        required: true
        type: string

  workflow_dispatch:
    inputs:
      target_branch:
        description: "Git branch to deploy from"
        type: string
        default: "main"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "website-deploy"
  cancel-in-progress: true

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.target_ref }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: actions/setup-node@v5
        with:
          node-version: "22.x"
      - uses: actions/configure-pages@v5

      - name: Update docs
        working-directory: .
        run: cargo xtask update-docs
      - run: npm ci
      - run: npm run build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: website/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
